---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  mss:
    name: Bake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 2
      - name: Build
        run: |
          set -euxo pipefail
          docker image list
          function ex() {
            bake=$1
            name=$2
            sfx=$3
            shift 3
            docker buildx bake --load $bake
            docker cp $(docker create "$@"):/usr/local/bin/totop$sfx totop-$name$sfx
          }
          ex linuxi linux-amd64 "" liftm/kafka-totop --platform linux/amd64
          ex linuxa64 linux-arm64 "" liftm/kafka-totop --platform linux/arm64
          ex win32 win-i32 .exe totop-win32
          ex win64 win-amd64 .exe totop-win64
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: |
            totop-win-i32.exe
            totop-win-amd64.exe
            totop-linux-amd64
            totop-linux-arm64

  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: mss
    steps:
      - uses: actions/download-artifact@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bins/totop-win-i32.exe
            bins/totop-win-amd64.exe
            bins/totop-linux-amd64
            bins/totop-linux-arm64
